// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYRD15ToDcXRw8tyBiwfJJRwwkpVzXm3Q',
    appId: '1:961779225294:web:fee6596a7ee33da3ee769f',
    messagingSenderId: '961779225294',
    projectId: 'cageid-ffa51',
    authDomain: 'cageid-ffa51.firebaseapp.com',
    storageBucket: 'cageid-ffa51.firebasestorage.app',
    measurementId: 'G-3BV0SNEP5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjcxSLr_QWGHfyLoknTDuD6F70y-VZvBA',
    appId: '1:961779225294:android:b81ab9bd61e9be13ee769f',
    messagingSenderId: '961779225294',
    projectId: 'cageid-ffa51',
    storageBucket: 'cageid-ffa51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwCtvE-RrKUjg4W9WMQuV60KaBJIfbGyg',
    appId: '1:961779225294:ios:c5d6a1d587d71ab1ee769f',
    messagingSenderId: '961779225294',
    projectId: 'cageid-ffa51',
    storageBucket: 'cageid-ffa51.firebasestorage.app',
    iosClientId: '961779225294-bm7m80v3dbfhr96b0gb931r397eaav40.apps.googleusercontent.com',
    iosBundleId: 'com.example.cageId',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwCtvE-RrKUjg4W9WMQuV60KaBJIfbGyg',
    appId: '1:961779225294:ios:c5d6a1d587d71ab1ee769f',
    messagingSenderId: '961779225294',
    projectId: 'cageid-ffa51',
    storageBucket: 'cageid-ffa51.firebasestorage.app',
    iosClientId: '961779225294-bm7m80v3dbfhr96b0gb931r397eaav40.apps.googleusercontent.com',
    iosBundleId: 'com.example.cageId',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYRD15ToDcXRw8tyBiwfJJRwwkpVzXm3Q',
    appId: '1:961779225294:web:75f961cf318ee8f9ee769f',
    messagingSenderId: '961779225294',
    projectId: 'cageid-ffa51',
    authDomain: 'cageid-ffa51.firebaseapp.com',
    storageBucket: 'cageid-ffa51.firebasestorage.app',
    measurementId: 'G-TQXTXRW6SL',
  );
}
